--- passforge/wordlist.lua
-- Embedded 1024-word English wordlist for the passphrase generator.
--
-- WHY 1024 WORDS
--   1024 = 2^10, so every word carries exactly log2(1024) = 10.00 bits of
--   entropy. A 4-word passphrase therefore has 40.00 bits, a 5-word one
--   50.00 bits - round numbers that make the entropy math in the README and
--   in `passforge pass --json` trivially verifiable. The passphrase module
--   reads the list size dynamically (wordlist.bits_per_word()), so even if
--   the list changes again the estimates stay correct.
--
-- CURATION
--   * 3-9 letters, common English, spread across the whole alphabet;
--   * no proper nouns beyond month names, no numerals, no profanity;
--   * no two entries differ only by a trailing "s" or "d" where avoidable,
--     to keep auto-complete-style human recall reliable;
--   * the list is alphabetically grouped; blocks of 16 words keep the file
--     diff-friendly (16 words = one display row in the audit tooling).
--
-- FORMAT
--   One word per line for easy diffing and easy counting. The module
--   enforces uniqueness at load time (a duplicate raises passforge.wordlist
--   error), and passphrase.lua reads the size dynamically via
--   wordlist.bits_per_word(), so the entropy estimates can never drift.

local compat = require("passforge.compat")

local M = {}

-- [001-016] a ----------------------------------------------------------------
local WORDS = {
  "able",
  "about",
  "above",
  "accept",
  "across",
  "act",
  "action",
  "adapt",
  "add",
  "address",
  "admire",
  "adult",
  "advice",
  "afford",
  "afraid",
  "afternoon",
  -- [017-032] a ----------------------------------------------------------------
  "again",
  "against",
  "agent",
  "agree",
  "ahead",
  "airport",
  "alarm",
  "album",
  "alert",
  "alive",
  "allow",
  "almost",
  "alone",
  "along",
  "already",
  "always",
  -- [033-048] a ----------------------------------------------------------------
  "amber",
  "anchor",
  "angle",
  "animal",
  "ankle",
  "answer",
  "antler",
  "anvil",
  "apple",
  "apply",
  "approve",
  "arch",
  "archive",
  "argue",
  "armor",
  "around",
  -- [049-064] a / b ------------------------------------------------------------
  "arrive",
  "arrow",
  "artist",
  "aspect",
  "assess",
  "assist",
  "assume",
  "attach",
  "attack",
  "attempt",
  "attend",
  "attic",
  "audience",
  "august",
  "aunt",
  "autumn",
  -- [065-080] b ----------------------------------------------------------------
  "baby",
  "back",
  "bacon",
  "badge",
  "bake",
  "balance",
  "balcony",
  "ball",
  "bamboo",
  "banana",
  "band",
  "banner",
  "bar",
  "bare",
  "bargain",
  "barrel",
  -- [081-096] b ----------------------------------------------------------------
  "base",
  "basement",
  "basic",
  "basket",
  "batch",
  "bath",
  "battery",
  "battle",
  "bay",
  "beach",
  "beacon",
  "beam",
  "bean",
  "bear",
  "beard",
  "beat",
  -- [097-112] b ----------------------------------------------------------------
  "beauty",
  "because",
  "become",
  "bed",
  "bee",
  "beef",
  "before",
  "begin",
  "behave",
  "behind",
  "belief",
  "believe",
  "bell",
  "belt",
  "bench",
  "bend",
  -- [113-128] b ----------------------------------------------------------------
  "beneath",
  "berry",
  "beside",
  "best",
  "better",
  "beyond",
  "bicycle",
  "bike",
  "bill",
  "bin",
  "bind",
  "bird",
  "birth",
  "biscuit",
  "bit",
  "bite",
  -- [129-144] b / c ------------------------------------------------------------
  "bitter",
  "blade",
  "blame",
  "blanket",
  "blast",
  "blaze",
  "blend",
  "bless",
  "blind",
  "block",
  "bloom",
  "blossom",
  "blouse",
  "board",
  "boat",
  "body",
  -- [145-160] c ----------------------------------------------------------------
  "cabin",
  "cable",
  "cactus",
  "cage",
  "cake",
  "calendar",
  "call",
  "calm",
  "camera",
  "camp",
  "canal",
  "candle",
  "candy",
  "canoe",
  "canvas",
  "canyon",
  -- [161-176] c ----------------------------------------------------------------
  "cap",
  "cape",
  "captain",
  "capture",
  "card",
  "care",
  "career",
  "careful",
  "cargo",
  "carp",
  "carpet",
  "carriage",
  "carrot",
  "carry",
  "cart",
  "cascade",
  -- [177-192] c ----------------------------------------------------------------
  "case",
  "cash",
  "cassette",
  "castle",
  "casual",
  "cat",
  "catalog",
  "catch",
  "cater",
  "cattle",
  "cause",
  "cave",
  "ceiling",
  "celebrate",
  "cell",
  "cement",
  -- [193-208] c ----------------------------------------------------------------
  "census",
  "center",
  "century",
  "cereal",
  "certain",
  "chair",
  "chalk",
  "chamber",
  "champion",
  "chance",
  "change",
  "channel",
  "chapel",
  "chapter",
  "char",
  "charm",
  -- [209-224] c ----------------------------------------------------------------
  "chart",
  "chase",
  "chat",
  "cheap",
  "check",
  "cheese",
  "chef",
  "cherry",
  "chess",
  "chest",
  "chew",
  "chief",
  "chill",
  "chimney",
  "choice",
  "choose",
  -- [225-240] d ----------------------------------------------------------------
  "daily",
  "dairy",
  "daisy",
  "damage",
  "damp",
  "dance",
  "danger",
  "daring",
  "dark",
  "dash",
  "data",
  "date",
  "dawn",
  "day",
  "deaf",
  "dead",
  -- [241-256] d / e ------------------------------------------------------------
  "debate",
  "debris",
  "decade",
  "december",
  "decide",
  "deck",
  "declare",
  "deep",
  "deer",
  "defeat",
  "defend",
  "define",
  "degree",
  "delay",
  "delight",
  "delete",
  -- [257-272] e ----------------------------------------------------------------
  "eager",
  "eagle",
  "early",
  "earn",
  "earth",
  "easy",
  "echo",
  "eclipse",
  "edge",
  "edit",
  "effort",
  "egg",
  "eight",
  "either",
  "elbow",
  "elder",
  -- [273-288] e ----------------------------------------------------------------
  "elect",
  "electric",
  "elegant",
  "element",
  "elephant",
  "elevate",
  "eleven",
  "elite",
  "email",
  "ember",
  "emblem",
  "embrace",
  "emerge",
  "emit",
  "emotion",
  "empress",
  -- [289-304] e / f ------------------------------------------------------------
  "empire",
  "employ",
  "empty",
  "enable",
  "enact",
  "enclose",
  "encounter",
  "encourage",
  "end",
  "endless",
  "endorse",
  "enemy",
  "energy",
  "engage",
  "enjoy",
  "engine",
  -- [305-320] f ----------------------------------------------------------------
  "fable",
  "fabric",
  "facade",
  "factory",
  "fade",
  "fail",
  "faint",
  "fair",
  "fall",
  "false",
  "fame",
  "family",
  "famous",
  "fan",
  "fang",
  "fancy",
  -- [321-336] f ----------------------------------------------------------------
  "farm",
  "fashion",
  "fast",
  "fat",
  "fate",
  "father",
  "fatigue",
  "fault",
  "favor",
  "feast",
  "feather",
  "feature",
  "february",
  "federal",
  "fee",
  "fellow",
  -- [337-352] f / g ------------------------------------------------------------
  "feed",
  "feel",
  "female",
  "fence",
  "ferry",
  "festival",
  "fetch",
  "fever",
  "few",
  "fiber",
  "fiction",
  "field",
  "fierce",
  "fifteen",
  "figure",
  "filter",
  -- [353-368] g ----------------------------------------------------------------
  "gadget",
  "gain",
  "galaxy",
  "gallery",
  "game",
  "gamma",
  "garage",
  "garden",
  "garlic",
  "gas",
  "gate",
  "gather",
  "gauge",
  "gear",
  "gem",
  "gene",
  -- [369-384] g ----------------------------------------------------------------
  "general",
  "generous",
  "genius",
  "gentle",
  "genuine",
  "gesture",
  "ghost",
  "giant",
  "gift",
  "ginger",
  "giraffe",
  "give",
  "glad",
  "glance",
  "gleam",
  "glass",
  -- [385-400] g / h ------------------------------------------------------------
  "glide",
  "globe",
  "glory",
  "glove",
  "glow",
  "goal",
  "goat",
  "gold",
  "golf",
  "gong",
  "good",
  "goose",
  "gorge",
  "govern",
  "grace",
  "grain",
  -- [401-416] h ----------------------------------------------------------------
  "habit",
  "hair",
  "half",
  "hall",
  "halt",
  "hammer",
  "hand",
  "handle",
  "hang",
  "happy",
  "harbor",
  "hard",
  "harp",
  "harvest",
  "hash",
  "haste",
  -- [417-432] h ----------------------------------------------------------------
  "hat",
  "hatch",
  "hate",
  "haven",
  "hazard",
  "hazel",
  "head",
  "heal",
  "health",
  "heap",
  "heart",
  "heat",
  "heaven",
  "heavy",
  "hedge",
  "heir",
  -- [433-448] h / i ------------------------------------------------------------
  "heel",
  "helm",
  "hello",
  "helmet",
  "help",
  "hen",
  "herb",
  "hero",
  "hidden",
  "high",
  "hike",
  "hill",
  "hockey",
  "hobby",
  "hollow",
  "honey",
  -- [449-464] i ----------------------------------------------------------------
  "ice",
  "icon",
  "idea",
  "ideal",
  "identify",
  "idle",
  "igloo",
  "ignore",
  "ill",
  "image",
  "imagine",
  "imitate",
  "immune",
  "impact",
  "impress",
  "import",
  -- [465-480] i / j ------------------------------------------------------------
  "inch",
  "include",
  "income",
  "increase",
  "index",
  "indicate",
  "indoor",
  "industry",
  "infant",
  "infect",
  "inform",
  "inhale",
  "initial",
  "inject",
  "inland",
  "inn",
  -- [481-496] j ----------------------------------------------------------------
  "jacket",
  "jade",
  "jaguar",
  "jam",
  "january",
  "jar",
  "jasmine",
  "jaw",
  "jazz",
  "jelly",
  "jewel",
  "jockey",
  "join",
  "joke",
  "journey",
  "joy",
  -- [497-512] k ----------------------------------------------------------------
  "kayak",
  "keen",
  "keep",
  "kelp",
  "kettle",
  "key",
  "kick",
  "kid",
  "kidney",
  "kind",
  "king",
  "kiss",
  "kitchen",
  "kite",
  "kitten",
  "knee",
  -- [513-528] l ----------------------------------------------------------------
  "label",
  "labor",
  "lace",
  "lack",
  "ladder",
  "lady",
  "lake",
  "lamp",
  "lance",
  "land",
  "lane",
  "language",
  "lantern",
  "lap",
  "large",
  "laser",
  -- [529-544] l ----------------------------------------------------------------
  "last",
  "late",
  "later",
  "latex",
  "laugh",
  "launch",
  "laundry",
  "lava",
  "law",
  "lawn",
  "layer",
  "lazy",
  "leader",
  "leaf",
  "league",
  "leak",
  -- [545-560] l / m ------------------------------------------------------------
  "learn",
  "lease",
  "leash",
  "least",
  "leather",
  "leave",
  "lecture",
  "ledge",
  "left",
  "legal",
  "legend",
  "lemon",
  "lend",
  "length",
  "lens",
  "level",
  -- [561-576] m ----------------------------------------------------------------
  "machine",
  "magic",
  "magnet",
  "maid",
  "mail",
  "main",
  "maintain",
  "major",
  "make",
  "male",
  "mall",
  "mammal",
  "man",
  "manage",
  "mandate",
  "mango",
  -- [577-592] m ----------------------------------------------------------------
  "manner",
  "mansion",
  "manual",
  "many",
  "maple",
  "marble",
  "march",
  "margin",
  "marine",
  "mark",
  "market",
  "maroon",
  "marriage",
  "marsh",
  "martial",
  "marvel",
  -- [593-608] m / n ------------------------------------------------------------
  "mask",
  "mason",
  "mass",
  "master",
  "mat",
  "match",
  "mate",
  "material",
  "math",
  "mattress",
  "mature",
  "maximum",
  "may",
  "mayor",
  "meadow",
  "meal",
  -- [609-624] n ----------------------------------------------------------------
  "nail",
  "name",
  "napkin",
  "narrow",
  "nation",
  "native",
  "nature",
  "navy",
  "near",
  "neat",
  "necessary",
  "neck",
  "nectar",
  "need",
  "needle",
  "negative",
  -- [625-640] n / o ------------------------------------------------------------
  "neglect",
  "neighbor",
  "neither",
  "nephew",
  "nerve",
  "nest",
  "net",
  "network",
  "neutral",
  "never",
  "new",
  "news",
  "next",
  "nice",
  "nickel",
  "niece",
  -- [641-656] o / p ------------------------------------------------------------
  "oak",
  "oasis",
  "oat",
  "obey",
  "object",
  "observe",
  "obtain",
  "obvious",
  "occasion",
  "occupy",
  "occur",
  "ocean",
  "october",
  "odd",
  "offer",
  "office",
  -- [657-672] p ----------------------------------------------------------------
  "pace",
  "pack",
  "packet",
  "pad",
  "paddle",
  "page",
  "paint",
  "pair",
  "palace",
  "palm",
  "pamphlet",
  "panel",
  "panic",
  "pansy",
  "pants",
  "paper",
  -- [673-688] p ----------------------------------------------------------------
  "parade",
  "parcel",
  "pardon",
  "parent",
  "park",
  "parlor",
  "parrot",
  "parsley",
  "part",
  "partner",
  "party",
  "pass",
  "passage",
  "passenger",
  "passion",
  "past",
  -- [689-704] p ----------------------------------------------------------------
  "paste",
  "pastry",
  "patch",
  "path",
  "patient",
  "patrol",
  "pattern",
  "pause",
  "pave",
  "payment",
  "peace",
  "peach",
  "peak",
  "peanut",
  "pearl",
  "pebble",
  -- [705-720] p / q ------------------------------------------------------------
  "pedal",
  "peel",
  "peer",
  "pen",
  "pencil",
  "penguin",
  "people",
  "pepper",
  "perch",
  "percent",
  "perfect",
  "perfume",
  "period",
  "permit",
  "person",
  "pet",
  -- [721-736] q ----------------------------------------------------------------
  "quartz",
  "queen",
  "quench",
  "quest",
  "quick",
  "quiet",
  "quill",
  "quilt",
  "quirk",
  "quiver",
  "quit",
  "quite",
  "quiz",
  "quota",
  "quote",
  "quotient",
  -- [737-752] r ----------------------------------------------------------------
  "rabbit",
  "race",
  "rack",
  "radar",
  "radiate",
  "raft",
  "rail",
  "rain",
  "raise",
  "rally",
  "ram",
  "ranch",
  "random",
  "range",
  "rapid",
  "rare",
  -- [753-768] r ----------------------------------------------------------------
  "rat",
  "rate",
  "rather",
  "raven",
  "ravine",
  "raw",
  "ray",
  "razor",
  "reach",
  "read",
  "ready",
  "real",
  "reap",
  "rebel",
  "recipe",
  "red",
  -- [769-784] r / s ------------------------------------------------------------
  "reduce",
  "reed",
  "reef",
  "refer",
  "reform",
  "refuge",
  "region",
  "regret",
  "regular",
  "reign",
  "relax",
  "release",
  "relief",
  "religion",
  "rely",
  "remain",
  -- [785-800] s ----------------------------------------------------------------
  "sack",
  "sacred",
  "saddle",
  "safe",
  "sage",
  "sail",
  "sailor",
  "salad",
  "sale",
  "salmon",
  "salt",
  "salute",
  "sample",
  "sand",
  "sandal",
  "sapphire",
  -- [801-816] s ----------------------------------------------------------------
  "sardine",
  "sash",
  "satin",
  "satisfy",
  "saturday",
  "sauce",
  "sauna",
  "save",
  "saw",
  "say",
  "scale",
  "scan",
  "scar",
  "scarce",
  "scarf",
  "scatter",
  -- [817-832] s ----------------------------------------------------------------
  "scene",
  "scent",
  "schedule",
  "scheme",
  "school",
  "science",
  "scissors",
  "score",
  "scout",
  "scrap",
  "screen",
  "screw",
  "script",
  "scroll",
  "sculpture",
  "sea",
  -- [833-848] s ----------------------------------------------------------------
  "seal",
  "search",
  "season",
  "seat",
  "second",
  "secret",
  "section",
  "secure",
  "seed",
  "seek",
  "segment",
  "seldom",
  "select",
  "self",
  "sell",
  "senate",
  -- [849-864] s / t ------------------------------------------------------------
  "send",
  "senior",
  "sense",
  "sentence",
  "september",
  "series",
  "servant",
  "session",
  "settle",
  "seven",
  "several",
  "shade",
  "shadow",
  "shake",
  "shall",
  "shame",
  -- [865-880] t ----------------------------------------------------------------
  "table",
  "tackle",
  "tag",
  "tail",
  "tailor",
  "take",
  "tale",
  "talent",
  "talk",
  "tall",
  "tame",
  "tan",
  "tangle",
  "tank",
  "tape",
  "target",
  -- [881-896] t ----------------------------------------------------------------
  "task",
  "taste",
  "tattoo",
  "taxi",
  "teach",
  "team",
  "tear",
  "tease",
  "technical",
  "teeth",
  "telephone",
  "tempest",
  "tell",
  "temper",
  "temple",
  "tempt",
  -- [897-912] t ----------------------------------------------------------------
  "ten",
  "tenant",
  "tend",
  "tender",
  "tennis",
  "tense",
  "tent",
  "term",
  "terrace",
  "terrain",
  "terrible",
  "test",
  "texture",
  "thank",
  "that",
  "theater",
  -- [913-928] t / u ------------------------------------------------------------
  "theme",
  "then",
  "theory",
  "thermal",
  "thick",
  "thief",
  "thigh",
  "thin",
  "thing",
  "think",
  "third",
  "thorn",
  "thorough",
  "though",
  "thread",
  "threat",
  -- [929-944] u / v ------------------------------------------------------------
  "umbrella",
  "uncle",
  "under",
  "undo",
  "unicorn",
  "uniform",
  "union",
  "unique",
  "unit",
  "universe",
  "unlock",
  "until",
  "upgrade",
  "upper",
  "uproar",
  "upward",
  -- [945-960] v ----------------------------------------------------------------
  "vacant",
  "vaccine",
  "vacuum",
  "vague",
  "valid",
  "valley",
  "value",
  "valve",
  "vanilla",
  "vanish",
  "vapor",
  "variety",
  "vast",
  "vault",
  "vector",
  "velvet",
  -- [961-976] w ----------------------------------------------------------------
  "wagon",
  "waist",
  "wait",
  "wake",
  "walk",
  "wall",
  "walnut",
  "want",
  "warehouse",
  "warm",
  "warn",
  "warp",
  "wash",
  "wasp",
  "waste",
  "watch",
  -- [977-992] w ----------------------------------------------------------------
  "water",
  "wave",
  "wax",
  "way",
  "weak",
  "wealth",
  "weapon",
  "wear",
  "weave",
  "website",
  "wedding",
  "wedge",
  "weed",
  "week",
  "weep",
  "weigh",
  -- [993-1008] w ---------------------------------------------------------------
  "welcome",
  "well",
  "west",
  "wet",
  "whale",
  "wharf",
  "wheat",
  "wheel",
  "when",
  "where",
  "whisk",
  "whistle",
  "white",
  "who",
  "whole",
  "wick",
  -- [1009-1024] x / y / z ------------------------------------------------------
  "xenon",
  "xylophone",
  "yawn",
  "year",
  "yeast",
  "yell",
  "yellow",
  "yes",
  "yesterday",
  "yield",
  "yoga",
  "yogurt",
  "young",
  "youth",
  "zebra",
  "zero",
}

-- Uniqueness is enforced at load time: a duplicated word would silently
-- shrink the keyspace while the entropy math kept assuming the full list.
local WORD_SET = {}
for i = 1, #WORDS do
  if WORD_SET[WORDS[i]] then
    compat.fail("wordlist", "duplicate word '%s' in embedded list", WORDS[i])
  end
  WORD_SET[WORDS[i]] = i
end

--- The full list as an array (copy-free: treat as read-only by convention).
function M.all()
  return WORDS
end

--- Number of embedded words (1024 in this release).
function M.count()
  return #WORDS
end

--- 1-based lookup, same contract as ipairs order; nil when out of range.
function M.at(i)
  return WORDS[i]
end

--- Case-insensitive membership test.
function M.contains(word)
  if type(word) ~= "string" then
    return false
  end
  return WORD_SET[word:lower()] ~= nil
end

--- 1-based index of word (case-insensitive) or nil.
function M.index_of(word)
  if type(word) ~= "string" then
    return nil
  end
  return WORD_SET[word:lower()]
end

--- Uniformly random word using the provided rng object (or the shared one).
function M.pick(rng)
  local source = rng or require("passforge.random").default()
  return WORDS[source:below(#WORDS) + 1]
end

--- Convenience alias used by the passphrase module.
M.random_word = M.pick

--- Bits of entropy per word: log2(#WORDS). For a 1024-word list this is
-- exactly 10.0; the passphrase module relies on that value dynamically so a
-- future word-list expansion keeps the math correct.
function M.bits_per_word()
  return compat.log2(#WORDS)
end

return M
